/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.finalprojects;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author reden
 */
public class Category extends javax.swing.JPanel {

    ArrayList<CategoryItem> categories = new ArrayList<>();
    Map<CategoryItem, Menu> menu = new LinkedHashMap<>();
    public CategoryItem selectedItem = null;
    
     public Category() {
        initComponents();
        MainScrollPane.getHorizontalScrollBar().setPreferredSize(new Dimension(0,0));
        MainScrollPane.getHorizontalScrollBar().setUnitIncrement(36);
        MainScrollPane.getViewport().setBorder(null);
        MainScrollPane.setViewportBorder(null);
        MainScrollPane.setBorder(null);
        this.setBackground(ColorTheme.primaryColor);
        categoryHolder.setBackground(ColorTheme.primaryColor);
        categoryPanel.setBackground(ColorTheme.primaryColor);
        for (int i = 0; i < 20; i++) {
            addCategoryItem(new CategoryItem(this));
        }
    }

    public void addCategoryItem(CategoryItem item)
    {
        categories.add(item);
        categoryPanel.add(item);
        Menu m = new Menu(item.getName() + categories.size() + "");
        m.setVisible(false);
        menuHolder.add(m);
        menu.put(item, m);
        menuHolder.revalidate();
        System.out.println("ADDED MENU");
        
    }
    
    public void changeSelectedItem(CategoryItem newSelectedItem)
    {
        if(selectedItem != null)
        {
            Menu m = menu.get(selectedItem);
            m.setVisible(false);
            selectedItem = newSelectedItem;
            Menu mm = menu.get(selectedItem);
            mm.setVisible(true);
        }else{
            selectedItem = newSelectedItem;
            Menu m = menu.get(selectedItem);
            m.setVisible(true);
        }
    }
    
    public void wipeCategoryItem()
    {
        categories.clear();
        menu.clear();
        categoryPanel.removeAll();
        categoryPanel.repaint();        
        categoryPanel.revalidate();
    }
    
    public void resetAllBackground()
    {
        for (int i = 0; i < categories.size(); i++) {
            categories.get(i).resetBackground();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainScrollPane = new javax.swing.JScrollPane();
        categoryHolder = new javax.swing.JPanel();
        categoryPanel = new javax.swing.JPanel();
        menuHolder = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(700, 660));
        setMinimumSize(new java.awt.Dimension(700, 660));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 660));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainScrollPane.setToolTipText("");
        MainScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        MainScrollPane.setMaximumSize(new java.awt.Dimension(660, 40));
        MainScrollPane.setMinimumSize(new java.awt.Dimension(660, 40));
        MainScrollPane.setPreferredSize(new java.awt.Dimension(660, 40));

        categoryHolder.setMaximumSize(new java.awt.Dimension(170, 80));
        categoryHolder.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        categoryPanel.setAutoscrolls(true);
        categoryPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 0));
        categoryHolder.add(categoryPanel);

        MainScrollPane.setViewportView(categoryHolder);

        add(MainScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 0, -1, -1));

        menuHolder.setMaximumSize(new java.awt.Dimension(660, 600));
        menuHolder.setMinimumSize(new java.awt.Dimension(660, 600));
        menuHolder.setPreferredSize(new java.awt.Dimension(660, 600));
        menuHolder.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        add(menuHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 660, 600));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane MainScrollPane;
    private javax.swing.JPanel categoryHolder;
    private javax.swing.JPanel categoryPanel;
    private javax.swing.JPanel menuHolder;
    // End of variables declaration//GEN-END:variables
}
