/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.finalprojects;

import java.awt.Dimension;
import java.util.ArrayList;

/**
 *
 * @author reden
 */
public class Category extends javax.swing.JPanel {

    ArrayList<CategoryItem> categories = new ArrayList<>();
    public CategoryItem selectedItem = null;
    /**
     * Creates new form Category
     */
    public Category() {
        initComponents();
        MainScrollPane.getHorizontalScrollBar().setPreferredSize(new Dimension(0,0));
        MainScrollPane.getHorizontalScrollBar().setUnitIncrement(36);
        MainScrollPane.getViewport().setBorder(null);
        MainScrollPane.setViewportBorder(null);
        MainScrollPane.setBorder(null);
        menuHolder.setBackground(ColorTheme.primaryColor);
        menuPanel.setBackground(ColorTheme.primaryColor);
        for (int i = 0; i < 20; i++) {
            CategoryItem item = new CategoryItem();
            addCategoryItem(item);
        }
    }

    public void addCategoryItem(CategoryItem item)
    {
        categories.add(item);
        menuPanel.add(item);
    }
    
    public void wipeCategoryItem()
    {
        categories.clear();
        menuPanel.repaint();        
        menuPanel.revalidate();
    }
    
    public void resetAllBackground()
    {
        for (int i = 0; i < categories.size(); i++) {
            categories.get(i).resetBackground();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainScrollPane = new javax.swing.JScrollPane();
        menuHolder = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1200, 90));
        setName(""); // NOI18N
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        MainScrollPane.setToolTipText("");
        MainScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        MainScrollPane.setPreferredSize(new java.awt.Dimension(1200, 60));

        menuHolder.setMaximumSize(new java.awt.Dimension(170, 80));
        menuHolder.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        menuPanel.setAutoscrolls(true);
        menuPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 0));
        menuHolder.add(menuPanel);

        MainScrollPane.setViewportView(menuHolder);

        add(MainScrollPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane MainScrollPane;
    private javax.swing.JPanel menuHolder;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
