/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.finalprojects;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author reden
 */
public class MCategory extends javax.swing.JPanel {

    /**
     * Creates new form MCategory
     */
    public MCategory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        addButton.setText("+");
        addButton.setPreferredSize(new java.awt.Dimension(80, 80));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        javax.swing.JButton categoryButton = new javax.swing.JButton();

        categoryButton.setText("CHICKEN JOY");
        categoryButton.setPreferredSize(new java.awt.Dimension(80, 80));
        add(categoryButton);
        repaint();
        revalidate();
        Main topFrame = (Main) SwingUtilities.getWindowAncestor(this);
        topFrame.menu_p.add(new MMenu());
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    // End of variables declaration//GEN-END:variables
}
