/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.finalprojects;

/**
 *
 * @author reden
 */
public class MMenu extends javax.swing.JPanel {

    /**
     * Creates new form MMenu
     */
    public MMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 100));
        add(jButton1);

        jButton2.setText("jButton1");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 100));
        add(jButton2);

        jButton3.setText("jButton1");
        jButton3.setPreferredSize(new java.awt.Dimension(100, 100));
        add(jButton3);

        jButton4.setText("jButton1");
        jButton4.setPreferredSize(new java.awt.Dimension(100, 100));
        add(jButton4);

        jButton5.setText("jButton1");
        jButton5.setPreferredSize(new java.awt.Dimension(100, 100));
        add(jButton5);

        jButton6.setText("jButton1");
        jButton6.setPreferredSize(new java.awt.Dimension(100, 100));
        add(jButton6);

        jButton7.setText("jButton1");
        jButton7.setPreferredSize(new java.awt.Dimension(100, 100));
        add(jButton7);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
