/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.finalprojects;

/**
 *
 * @author reden
 */
public class ReceiptItem extends javax.swing.JPanel {

    /**
     * Creates new form ReceiptItem
     */
    public ReceiptItem() {
        initComponents();
        this.setBackground(ColorTheme.secondaryColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 40));
        setMinimumSize(new java.awt.Dimension(400, 40));
        setPreferredSize(new java.awt.Dimension(400, 40));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete (1).png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 40, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("P56.00");
        jLabel2.setMaximumSize(new java.awt.Dimension(140, 40));
        jLabel2.setMinimumSize(new java.awt.Dimension(140, 40));
        jLabel2.setPreferredSize(new java.awt.Dimension(140, 40));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 70, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("<html>1 PC. CHICKEN LEGS</html>");
        jLabel3.setMaximumSize(new java.awt.Dimension(140, 40));
        jLabel3.setMinimumSize(new java.awt.Dimension(140, 40));
        jLabel3.setPreferredSize(new java.awt.Dimension(140, 40));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("1");
        jLabel4.setMaximumSize(new java.awt.Dimension(140, 40));
        jLabel4.setMinimumSize(new java.awt.Dimension(140, 40));
        jLabel4.setPreferredSize(new java.awt.Dimension(140, 40));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 40, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
